site_name: FlagBytes
site_description: Cybersecurity Notes and CTF Writeups

theme:
  name: material

  palette:
    - scheme: slate
      primary: black
      accent: green

  font:
    text: Inter
    code: JetBrains Mono

  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md

  - CTFs:
      - Overview: ctf.md
      - Lets Warm Up: lets-warm-up.md